apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: avishai-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: avishaihaasz:22
        ports:
        - containerPort: 8080
