apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-svc
  namespace: avishai-home
spec:
  selector:
    app: dotnet-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080       # Port exposed by the service internally
      targetPort: 8080 # Port on the pods that the service is targeting
      nodePort: 30080  # Port allocated on every node in the cluster
